config/routes.rb
Rails.application.routes.draw do
  get 'org_chart/org_chart'

  get 'add_documents/add_documents'

  get 'profile/profile'

  get 'attendance/index'

  get 'onboard/onboard'

  get 'employees/employees'

  get 'controller_name/page_name'

  get 'leaves/index'

  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :leaves, :employees, :onboard, :profile, :attendance
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :user
  mount_uploader :attachment, AttachmentUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :leaves, dependent: :destroy
  belongs_to :role
  before_create :set_default_role

  private
  def set_default_role
    self.role ||= Role.find_by_name('user')
  end
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
    def index
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def employees
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  def index
    @leaves = Leave.all
    @leave = Leave.new
  end

  def create
        binding.pry

    @leave = current_user.leaves.new(leave_params)
    if @leave.save
      redirect_to leaves_path
    else
      flash[:error] = "#{@leave.errors.full_messages}"
      redirect_to leaves_path
    end
  end

  private

  def leave_params
    params.require(:leave).permit!
  end
end

app/controllers/onboard_controller.rb
class OnboardController < ApplicationController
  def onboard
  end
end

app/controllers/org_chart_controller.rb
class OrgChartController < ApplicationController
  def org_chart
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def profile
  end
end

app/helpers/add_documents_helper.rb
module AddDocumentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/controller_name_helper.rb
module ControllerNameHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/onboard_employees_helper.rb
module OnboardEmployeesHelper
end

app/helpers/onboard_helper.rb
module OnboardHelper
end

app/helpers/org_chart_helper.rb
module OrgChartHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/employees/employees.html.erb
<h1>Employees#employees</h1>
<p>Find me in app/views/employees/employees.html.erb</p>

app/views/employees/index.html.erb
<!-- Scrollbar Custom CSS -->
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
  
    <div class="sidebar-sticky">
      <div class="sidebar-header">
        <img src="/assets/logo.png" class="img-fluid d-none d-md-block" alt="HRMS">
      </div>

      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-bookmark"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item active has-sub-menu">
        <a class="nav-link" href="<%= employees_path %>">
          <i class="la la-users"></i>
          <span>Employees</span>
        </a>
        <i class="la la-angle-right sub-menu-click"></i>

        <div class="sub-menu">
          <ul class="list-unstyled">
            <li><a href="<%= onboard_onboard_path %>">Onboard</a></li>
            <li><a href="">Offboard</a></li>
            <li><a href="<%= attendance_index_path %>">Attendance</a></li>
            </ul>
        </div>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= leaves_path %>">
            <i class="la la-clock-o"></i>
            <span>Leaves</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-list-alt"></i>
            <span>Tasks</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
           <i class="la la-money"></i>
            <span>Payroll</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= add_documents_add_documents_path %>">
            <i class="la la-file-text-o"></i>
            <span>Documents</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-certificate"></i>
            <span>Appraisal</span>
          </a>
        </li>
      
        <li class="nav-item">
        <a class="nav-link" href="<%= org_chart_org_chart_path %>">
        <i class="la la-sitemap"></i>
            <span>Organisation List</span>
        </a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-question"></i>
            <span>Help</span>
          </a>
        </li>
      </ul>

      <div class="sidebar-footer">
        <ul class="list-inline">
          <li class="list-inline-item">
                            <a href="<%= profile_profile_path %>">
                             <img class="img-avatar" src="/assets/person.jpg">
                            </a>
          </li>
           <li class="list-inline-item">
            <a class="" href="#" title="Notifications"><i class="la la-bell"></i>
                <span class="badge-pulse pulse-warning"></span>
            </a>
          </li>
           <li class="list-inline-item">
            <a class="" href="#" title="Settings"><i class="la la-gear"></i>
              </a>
          </li>
          <li class="list-inline-item">
            <a class="" href="#" title="Log Out"><i class="la la-sign-out"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content  -->
  <div id="content">

    <!-- Dashboard -->
    <div class="dashboard">




<!------------------------------ Employee Search ------------------------------------------>
<div class="page-wrapper">
            <div class="page-header">
                <div class="row">
              <div class="col-md-9">
                  <h2>Employees</h2>
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Employees List</li>
                  </ol>
                </nav>
             </div>
              <div class="col-md-3">
                <!-- Button trigger modal -->
                <a class="btn btn-default pull-right" href="<%= onboard_onboard_path %>">
                  Onboard Employee
                </a>
              </div>
            </div>
             </div>

 <div class="filter-employees">
             <div class="row">
              <div class="col-sm-12">
                <h4 class="section-title">Search Employees</h4>
              </div>
               <div class="col-sm-4">
                 <input type="search" class="form-control" placeholder="Enter Keyword">
              </div>
              <div class="col-sm-4">
                 <select class="selectpicker form-control" title="Department" data-live-search="true">
                      <option data-tokens="IT">Information Technology</option>
                      <option data-tokens="Finance">Finance</option>
                      <option data-tokens="Human Resource">Human Resource</option>
                    </select>
              </div>
               <div class="col-sm-4">
                 <input type="text" class="form-control" placeholder="Work Location">
              </div>
             </div>
             

             </div>

          <div class="row">
            

              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person3.jpg">
                  </div>
                    <div class="card-body">
                      <div class="options">
                                <div class="dropdown show">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="la la-ellipsis-v"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-arrow" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item" href="#">Profile</a>
                              <a class="dropdown-item" href="#">Team</a>
                            </div>
                          </div>
                      </div>
              

                      <h4 class="card-title">Shahil Mohammed</h4>
                      <p class="card-text">Senior Software Engineer</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-994-560-9605</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>shahil@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Mangalore</span>
                    </div>
              </div>
              </div>

              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person.jpg">
                  </div>
                    <div class="card-body">
                      <h4 class="card-title">Anjana Raveendran</h4>
                      <p class="card-text">Programmer Analyist</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-995-125-8590</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>anjana@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Bangalore</span>
                    </div>
              </div>
              </div>


              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person4.jpg">
                  </div>
                    <div class="card-body">
                      <h4 class="card-title">Ranjith Jogi</h4>
                      <p class="card-text">Technical Head</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-897-114-9551</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>ranjith@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Bangalore</span>
                    </div>
              </div>
              </div>


              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person3.jpg">
                  </div>
                    <div class="card-body">
                       <div class="options">
                                <div class="dropdown show">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="la la-ellipsis-v"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-arrow" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item" href="#">Profile</a>
                              <a class="dropdown-item" href="#">Team</a>
                            </div>
                          </div>
                      </div>
              
                      <h4 class="card-title">James Mathew</h4>
                      <p class="card-text">Software Engineer</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-586-560-8598</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>james@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Mangalore</span>
                    </div>
              </div>
              </div>


              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person2.jpg">
                  </div>
                    <div class="card-body">
                      <h4 class="card-title">Chris Kelvin</h4>
                      <p class="card-text">Assosiate Team Lead</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-748-560-6622</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>chris@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Mangalore</span>
                    </div>
              </div>
              </div>



              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person.jpg">
                  </div>
                    <div class="card-body">
                       <div class="options">
                                <div class="dropdown show">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="la la-ellipsis-v"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-arrow" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item" href="#">Profile</a>
                              <a class="dropdown-item" href="#">Team</a>
                            </div>
                          </div>
                      </div>
              
                      <h4 class="card-title">Ashley Montana</h4>
                      <p class="card-text">HR Lead</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-589-560-9605</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>ashley@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Hydrabad</span>
                    </div>
              </div>
              </div>


              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person3.jpg">
                  </div>
                    <div class="card-body">
                      <h4 class="card-title">Mellisa Mark</h4>
                      <p class="card-text">Junior Software Engineer</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-994-560-9605</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>shahil@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Mangalore</span>
                    </div>
              </div>
              </div>


              <div class="col-md-3">
              <div class="card employee-card">
                  <div class="card-header">
                    <img class="card-img-top rounded-circle" src="assets/person.jpg">
                  </div>
                    <div class="card-body">
                      <h4 class="card-title">Shahil Mohammed</h4>
                      <p class="card-text">Senior Software Engineer</p>
                      <span class="d-block"><i class="la la-phone"></i>+91-994-560-9605</span>
                      <span class="d-block"><i class="la la-envelope-o"></i>shahil@folkslogic.com</span>
                       <span class="d-block"><i class="la la-map-marker"></i>Mangalore</span>
                    </div>
              </div>
              </div>
          </div>





</div>

  </div>
</div>

app/views/home/index.html.erb
<!-- Scrollbar Custom CSS -->
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
  
    <div class="sidebar-sticky">
      <div class="sidebar-header">
        <img src="/assets/logo.png" class="img-fluid d-none d-md-block" alt="HRMS">
      </div>

      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-bookmark"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item has-sub-menu">
        <a class="nav-link" href="<%= employees_path %>">
          <i class="la la-users"></i>
          <span>Employees</span>
        </a>
        <i class="la la-angle-right sub-menu-click"></i>

        <div class="sub-menu">
          <ul class="list-unstyled">
            <li><a class="" href="<%= onboard_onboard_path %>">Onboard</a></li>
            <li><a href="">Offboard</a></li>
            <li><a href="<%= attendance_index_path %>">Attendance</a></li>
            </ul>
        </div>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= leaves_path %>">
            <i class="la la-clock-o"></i>
            <span>Leaves</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-list-alt"></i>
            <span>Tasks</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
           <i class="la la-money"></i>
            <span>Payroll</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= add_documents_add_documents_path %>">
            <i class="la la-file-text-o"></i>
            <span>Documents</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-certificate"></i>
            <span>Appraisal</span>
          </a>
        </li>
        
        <li class="nav-item">
        <a class="nav-link" href="<%= org_chart_org_chart_path %>">
        <i class="la la-sitemap"></i>
            <span>Organisation List</span>
        </a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-question"></i>
            <span>Help</span>
          </a>
        </li>
      </ul>

      <div class="sidebar-footer">
        <ul class="list-inline">
          <li class="list-inline-item">
                            <a href="<%= profile_profile_path %>">
                             <img class="img-avatar" src="/assets/person.jpg">
                            </a>
          </li>
           <li class="list-inline-item">
            <a class="" href="#" title="Notifications"><i class="la la-bell"></i>
                <span class="badge-pulse pulse-warning"></span>
            </a>
          </li>
           <li class="list-inline-item">
            <a class="" href="#" title="Settings"><i class="la la-gear"></i>
              </a>
          </li>
          <li class="list-inline-item">
            <a class="" href="#" title="Log Out"><i class="la la-sign-out"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content  -->
  <div id="content">

    <!-- Dashboard -->
    <div class="dashboard">



    <!-- //Dashboard -->
  </div>
</div>

app/views/org_chart/org_chart.html.erb
<!-- Scrollbar Custom CSS -->
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
  
    <div class="sidebar-sticky">
      <div class="sidebar-header">
        <img src="/assets/logo.png" class="img-fluid d-none d-md-block" alt="HRMS">
      </div>

      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-bookmark"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item has-sub-menu">
        <a class="nav-link" href="<%= employees_path %>">
          <i class="la la-users"></i>
          <span>Employees</span>
        </a>
        <i class="la la-angle-right sub-menu-click"></i>

        <div class="sub-menu">
          <ul class="list-unstyled">
            <li><a href="<%= onboard_onboard_path %>">Onboard</a></li>
            <li><a href="">Offboard</a></li>
            <li><a href="<%= attendance_index_path %>">Attendance</a></li>
            </ul>
        </div>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= leaves_path %>">
            <i class="la la-clock-o"></i>
            <span>Leaves</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-list-alt"></i>
            <span>Tasks</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
           <i class="la la-money"></i>
            <span>Payroll</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= add_documents_add_documents_path %>">
            <i class="la la-file-text-o"></i>
            <span>Documents</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-certificate"></i>
            <span>Appraisal</span>
          </a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="<%= org_chart_org_chart_path %>">
        <i class="la la-sitemap"></i>
            <span>Organisation List</span>
        </a>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="la la-question"></i>
            <span>Help</span>
          </a>
        </li>
      </ul>

      <div class="sidebar-footer">
        <ul class="list-inline">
          <li class="list-inline-item">
                            <a href="<%= profile_profile_path %>">
                             <img class="img-avatar" src="/assets/person.jpg">
                            </a>
          </li>
           <li class="list-inline-item">
            <a class="" href="#" title="Notifications"><i class="la la-bell"></i>
                <span class="badge-pulse pulse-warning"></span>
            </a>
          </li>
           <li class="list-inline-item">
            <a class="" href="#" title="Settings"><i class="la la-gear"></i>
              </a>
          </li>
          <li class="list-inline-item">
            <a class="" href="#" title="Log Out"><i class="la la-sign-out"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content  -->
  <div id="content">

    <!-- Dashboard -->
    <div class="dashboard">





<div class="page-wrapper">
            <div class="page-header">
                <div class="row">
              <div class="col-md-9">
                  <h2>Organisation List</h2>
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Org List</li>
                  </ol>
                </nav>
             </div>
              <div class="col-md-3">
               <a class="btn btn-default pull-right" href="<%= onboard_onboard_path %>">
                  <i class="la la-pencil"></i> Edit Profile
               </a>
             
              </div>
            </div>
             </div>

 

          <div class="row">

            <div class="col-sm-12">
     

            <div id="tree"></div>





            
          </div>





    </div>





</div>

</div>



<script type="text/javascript">
  
window.onload = function () {
  //OrgChart.templates.ana.img_0 = '<image preserveAspectRatio="xMidYMid slice" xlink:href="{val}" x="20" y="-10" width="80" height="80"></image>';
  OrgChart.templates.ana.field_0 = '<text class="field_0" x="75" y="100" style="font-size: 22px;" text-anchor="middle">{val}</text>';
  //OrgChart.templates.ana.field_1 = '<text class="field_1"  style="font-size: 12px;" x="200" y="50" text-anchor="middle">{val}</text>';

  var chart = new OrgChart(document.getElementById("tree"), {
      scaleInitial: BALKANGraph.match.boundary,
      enableDragDrop: false,
      enablePrint: true,
      enableSearch: false,
      mouseScroolBehaviour: BALKANGraph.action.zoom,
      nodeBinding: {
          field_0: "name",
          field_1: "title",
          img_0: "img"
      },
      nodes: [
          { id: 1, name: "Denny Curtis", title: "CEO", img: "https://balkangraph.com/js/img/2.jpg" },

          { id: 2, pid: 1, name: "Ashley Barnett", title: "Sales Manager", img: "https://balkangraph.com/js/img/3.jpg" },
          { id: 3, pid: 1, name: "Caden Ellison", title: "Dev Manager", img: "https://balkangraph.com/js/img/4.jpg" },
          { id: 4, pid: 2, name: "Caden Ellison", title: "Dev Manager", img: "https://balkangraph.com/js/img/4.jpg" },

          { id: 4, pid: 2, name: "Elliot Patel", title: "Sales", img: "https://balkangraph.com/js/img/5.jpg" },
          { id: 5, pid: 3, name: "Lynn Hussain", title: "Sales", img: "https://balkangraph.com/js/img/6.jpg" },

          { id: 6, pid: 2, name: "Ashley Barnett", title: "Sales Manager", img: "https://balkangraph.com/js/img/3.jpg" },
          { id: 7, pid: 3, name: "Caden Ellison", title: "Dev Manager", img: "https://balkangraph.com/js/img/4.jpg" },

          { id: 8, pid: 6, name: "Tanner May", title: "Developer", img: "https://balkangraph.com/js/img/7.jpg" },
          { id: 9, pid: 6, name: "Fran Parsons", title: "Developer", img: "https://balkangraph.com/js/img/8.jpg" },
          { id: 10, pid: 7, name: "Rudy Griffiths", title: "Assistant", img: "https://balkangraph.com/js/img/9.jpg" },
          { id: 11, pid: 7, name: "Skyler Hunt", title: "Assistant", img: "https://balkangraph.com/js/img/12.jpg" },
          { id: 12, pid: 10, name: "Elliot Patel", title: "Sales", img: "https://balkangraph.com/js/img/5.jpg" },
          { id: 13, pid: 10, name: "Lynn Hussain", title: "Sales", img: "https://balkangraph.com/js/img/6.jpg" },
          { id: 14, pid: 10, name: "Elliot Patel", title: "Sales", img: "https://balkangraph.com/js/img/5.jpg" },
          { id: 15, pid: 10, name: "Lynn Hussain", title: "Sales", img: "https://balkangraph.com/js/img/6.jpg" }
      ]
  });
};
          
 
  </script>     